<?php
/** @var \ElQuchiri\SocialLogin\Block\SocialBlock $block */
?>
<? if($block->IsSocialLoginActive() && count($block->getEnabledSocialNetworks()) > 0): ?>
<div class="block block-customer-login">
    <!-- Social Login container -->
    <div class="social-login-container">
        <div class="block-title">
            <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Or You can login via Social Networks')) ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <ul>
                <?php foreach($block->getEnabledSocialNetworks() as $key => $socialNetwork): ?>
                <li><a class="<?= $key ?>" href="#"></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <!-- End Social Login container -->

    <script type="text/x-magento-init">
        {
            "*": {
                "providerWindowOpener": {}
            }
        }
    </script>
</div>
<? endif; ?>